import type { Metadata } from "next";
import {Bitter} from 'next/font/google';

import Providers from "./providers";
import "./globals.css";

const bitter = Bitter({
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Big Fish",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={bitter.className} suppressHydrationWarning>
      <body
      >
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
