import type { Metadata } from 'next';
import { Bitter } from 'next/font/google';

import Providers from './providers';
import MainNav from '@/components/navigation/MainNav';
import './globals.css';

const bitter = Bitter({
	subsets: ['latin'],
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Big Fish',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className={bitter.className} suppressHydrationWarning>
			<body className='flex bg-gradient-to-r from-indigo-400 to-cyan-400 dark:from-blue-800 dark:to-violet-700'>
				<Providers>
					<MainNav />
					<main className='container mx-auto min-h-screen grow'>
						{children}
					</main>
				</Providers>
			</body>
		</html>
	);
}
